apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster-application-set
  namespace: argocd
spec:
  generators:
  - cluster: cluster-2
    url: https://10.5.0.81:6443
  - cluster: cluster-3
    url: https://10.5.0.184:6443
  template:      
    metadata:
      name: '{{name}}-billing-app'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/Jeet-14/k8s-instore.git
        targetRevision: HEAD
        path: my-yaml/{{cluster}}
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: '{{server}}'
        namespace: default

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      
